---
title: "LIMPIEZAGENERAL"
author: "Joel B. Hu y Fabian Rios"
output: html_document
date: "2022-10-07"
---

 - VARIABLE DEPENDIENTE: DESEMPLEO 
  
```{r}
library(rio)
data0="https://github.com/20181496/Trabajo-final-Estadistica-2/files/9936907/desempleoBM.csv"
desempleo=import(data0)
```

```{r}
#Borrando Filas 
desempleo = desempleo[-c(1:4, 6, 8),]

#seleccionando pais y inverext
library(dplyr)
desempleojuve <- select(desempleo, 'Data Source','_60') 

#Renombrando las columnas seleccionadas:
colnames(desempleojuve) = c("pais","desempleojuv")
```


##LIMPIEZA JOEL

  - INVERSION EXTRANJERA:
  
```{r}
library(rio)
data1="https://github.com/20181496/Trabajo-final-Estadistica-2/files/9936930/inverex.csv"
datainver=import(data1)
```

```{r}
#Borrando Filas 
datainver = datainver[-c(1:4, 6, 8),]

#seleccionando pais y inverext
library(dplyr)
inverextranjera <- select(datainver, 'Data Source','_60') 

#Renombrando las columnas seleccionadas:
colnames(inverextranjera) = c("pais","inverex")
```

  - CRECIMIENTO DEL PBI:
  
```{r}
data2="https://github.com/20181496/Trabajo-final-Estadistica-2/files/9936920/PBI.csv"
dataPBI=import(data2)
```

```{r}
#Borrando Filas 
dataPBI = dataPBI[-c(1:4, 6, 8),]

#seleccionando pais y PBI
CreciPBI <- select(dataPBI, 'Data Source','_60') 

#Renombrando las columnas seleccionadas:
colnames(CreciPBI) = c("pais","PBI")
```

##LIMPIEZA FABIAN
  
 - Obesidad en adultos

```{r}
data3="https://github.com/20181496/Trabajo-final-Estadistica-2/files/9936917/ObesidadCIA.csv"
dataobeadult=import(data3)

head(dataobeadult)
```

  - Se aplica la limpieza

```{r}

#seleccionando name y value
library(dplyr)
obesidad <- select(dataobeadult, "name", "value") 

#Renombrando las columnas seleccionadas:
colnames(obesidad) = c("pais","obeadult")
```


  - Gastos en educacion
```{r}
data4="https://github.com/20181496/Trabajo-final-Estadistica-2/files/9936914/GastosEdu.csv"
datagastoedu=import(data4)
```

```{r}
#seleccionando name y value
library(dplyr)
gastoseduc <- select(datagastoedu, "name", "value") 

#Renombrando las columnas seleccionadas:
colnames(gastoseduc) = c("pais","gastoseduc")
```
  
  - Infraestructura de Transito

```{r}
data5="https://github.com/20181496/Trabajo-final-Estadistica-2/files/9936912/RoadW.csv"
datatransito=import(data5)
```

```{r}
#seleccionando name y value
library(dplyr)
transito <- select(datatransito, "name", "value") 

#Renombrando las columnas seleccionadas:
colnames(transito) = c("pais","transito")
```


##Merging

  - JOEL: data12
  
```{r}
data12=merge(inverextranjera,CreciPBI, by = "pais")

str(data12)
```

```{r}
data12[which(is.na(data12$PBI)),]
sum(is.na(data12$PBI))

data12[which(is.na(data12$inverex)),]
sum(is.na(data12$inverex))
```


- VARIABLE DEPENDIENTE y transito: dataVD5
  
```{r}
dataVD5=merge(desempleojuve,transito, by = "pais")

dataVD5[which(is.na(dataVD5$desempleojuve)),]
sum(is.na(dataVD5$desempleojuve))

dataVD5[which(is.na(dataVD5$transito)),]
sum(is.na(dataVD5$transito))
```


  - FABIAN: data34
```{r}
data34=merge(obesidad,gastoseduc, by = "pais")
str(data34)
```

```{r}
data34[which(is.na(data34$obesidad)),]
sum(is.na(data34$obesidad))

data34[which(is.na(data34$gastoseduc)),]
sum(is.na(data34$gastoseduc))
```


  - Unificando ambas:
```{r}
datapuente=merge(data12,dataVD5, by = "pais") 
```


```{r}
DATALIMPIA=merge(datapuente,data34, by = "pais")
str(DATALIMPIA)
```

```{r}
DATALIMPIA <- na.omit(DATALIMPIA)
```
X


```{r}
library(rio)
export(DATALIMPIA, "DATALIMPIA.csv")
```



  
  