---
title: "Limpieza de datos"
author: "Jose Rios"
date: "2022-09-09"
output: html_document
---


```{r}
library(htmltab)
library(rio)
library(readr)
```


#Variable dependiente del desempleo de jovenes de 15 a 22 años 


```{r}
Desempleo <- read_csv("Desempleo.csv")
head(Desempleo)
```
Se aplica la limpieza
```{r}
Desempleo$slug<-NULL
Desempleo$date_of_information<-NULL
Desempleo$ranking<-NULL
Desempleo$region<-NULL
Desempleo$Desempleo=Desempleo$value
Desempleo$value<-NULL
Desempleo$Desempleo<- as.numeric(Desempleo$Desempleo)
gsub(" ","",Desempleo)
```

```{r}
head(Desempleo)
```


#variable de obesidad en adultos


```{r}
ObesidadAdult <- read_csv("ObesidadAdult.csv")
head(ObesidadAdult)
```

Se aplica la limpieza

```{r}
ObesidadAdult$slug <-NULL
ObesidadAdult$date_of_information <-NULL
ObesidadAdult$ranking <-NULL
ObesidadAdult$region <-NULL
ObesidadAdult$ObesidadAdultos=ObesidadAdult$value
ObesidadAdult$value<-NULL
ObesidadAdult$ObesidadAdultos<-as.numeric(ObesidadAdult$ObesidadAdultos)
gsub(" ","",ObesidadAdult)
head(ObesidadAdult)
```



#Variable de gastos en educacion


```{r}
GastosEdu <- read_csv("GastosEdu.csv")
head(GastosEdu)
```
Se procede a limpiar los datos
```{r}
GastosEdu$slug <-NULL
GastosEdu$date_of_information <-NULL
GastosEdu$ranking <-NULL
GastosEdu$region<-NULL
GastosEdu$GastosEducacion=GastosEdu$value

GastosEdu$value<-NULL

GastosEdu$GastosEducacion<-as.numeric(GastosEdu$GastosEducacion)
gsub(" ","",GastosEdu)
head(GastosEdu)
```



#Variable de libertad civica


```{r}
library(dplyr)
library(stringr)
linkE='https://en.wikipedia.org/wiki/Democracy_Index'
xpathE='/html/body/div[3]/div[3]/div[5]/div[1]/table[6]'
LiCiv= htmltab(linkE,xpathE)
str_remove_all(LiCiv$name," ")
head(LiCiv)
```
Se limpia la data
```{r}
LiCiv$`Rank >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`Elec­toral pro­cessand plura­lism >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`Func­tioningof govern­ment >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`Poli­ticalpartici­pation >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`Poli­ticalcul­ture >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Δ Rank >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`Δ Score >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`Overall score >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$`Regime type >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes` <-NULL
LiCiv$name=LiCiv$`Country >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes`
LiCiv$`Country >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes`<-NULL
LiCiv$LibertadCivil=LiCiv$`Civilliber­ties >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes`
LiCiv$`Civilliber­ties >> Full democracies >> Flawed democracies >> Hybrid regimes >> Authoritarian regimes`<-NULL
LiCiv$LibertadCivil<-as.numeric(LiCiv$LibertadCivil)

```

```{r}
gsub(" ","",LiCiv)
head(LiCiv)
```
#Infraestructura de Transito
```{r}
RoadW <- read_csv("RoadW.csv")
head(RoadW)
```
#Se Limpia la data
```{r}
RoadW$slug<-NULL
RoadW$date_of_information <-NULL
RoadW$ranking <-NULL
RoadW$region <-NULL
RoadW$KMVia<-as.numeric(RoadW$value)
RoadW$value<-NULL
head(RoadW)
```



#Se forma la database a usar

```{r}
DataBaseP1=merge(Desempleo,GastosEdu,by='name')
```

```{r}
library(dplyr)
```

```{r}
DataBaseP2<-DataBaseP1%>%full_join(RoadW)

DataBaseP3<-DataBaseP2%>%full_join(ObesidadAdult)
DataBase4<-DataBaseP3%>%full_join(LiCiv)
```
Creando la database
```{r}
  write.csv(DataBase4,"/Users/fabianrios/Desktop/2022-2/Estadistica 2/Trabajo Grupal/DataBase.csv",row.names = TRUE)
```










